MyStore/Areas/Admin/Controllers/AuthAdminController.cs
using MyClass.DAO;
using MyStore.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyStore.Areas.Admin.Controllers
{
    public class AuthAdminController : Controller
    {
        private readonly Services.AuthenticationService _authenticationService = new Services.AuthenticationService();
        UsersDAO usersDAO = new UsersDAO();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password)
        {
            var user = usersDAO.getUser(username, password);
            if (user != null && user.Status == 1)
            {
                if (user.Role == "admin")
                {
                    SessionConfig.SetUser(user);
                    Session["user"] = SessionConfig.GetUser();
                    return RedirectToAction("Index", "Dashboard");
                }
                ViewBag.Login = "Tài khoản không được quyền đăng nhập!";
                return View();
            }
            ViewBag.Login = "Đăng nhập không thành công!";
            return View();
        }
        public ActionResult Logout()
        {
            SessionConfig.SetUser(null);
            return RedirectToAction("Login");
        }
    }
}

MyStore/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyClass.DAO;
using MyClass.Model;
using MyStore.App_Start;
using MyStore.Libarary;

namespace MyStore.Controllers
{
    public class SiteController : Controller
    {
        private MyDBContext db = new MyDBContext();
        ProductsDAO productsDAO = new ProductsDAO();
        CategoriesDAO categoriesDAO = new CategoriesDAO();
        public ActionResult Index()
        {
            var listSP = productsDAO.getList();
            var listCat = categoriesDAO.getList();
            ViewBag.Products = listSP;
            ViewBag.Categories = listCat;
            
            return View(listSP);

        }
        public ActionResult Product() 
        {
            var listSP = productsDAO.getList();
            var listCat = categoriesDAO.getList();
            ViewBag.Categories = listCat;
            return View(listSP);
        }
        [HttpPost]
        public ActionResult Product(string filter)
        {
            var listSP = productsDAO.getList();
            var listCat = categoriesDAO.getList();
            ViewBag.Categories = listCat;
            List<Products> listNews = db.Products.Where(m => m.Name.ToLower().Contains(filter.ToLower()) == true).ToList();
            if(listNews.Count > 0)
            {
                return View(listNews);
            }
            return View(listSP);
        }
        public ActionResult DetailProduct(int? id)
        {
            var listCat = categoriesDAO.getList();
            ViewBag.Categories = listCat;
            if (id != null)
            {
                var pro = productsDAO.getRow(id);
                return View(pro);
            }
            else
            {
                return View();
            }
        }
        
    }
}

MyStore/Areas/Admin/Views/AuthAdmin/Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in (v2)</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Public/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Public/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Public/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="~/Public/index2.html" class="h1"><b>Admin</b>LTE</a>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                @using (Html.BeginForm("Login", "AuthAdmin", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Usrname" name="username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                }
                <p class="text-danger text-center mt-2">@ViewBag.Login</p>
                <div class="social-auth-links text-center mt-2 mb-3">
                    <a href="#" class="btn btn-block btn-primary">
                        <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                    </a>
                    <a href="#" class="btn btn-block btn-danger">
                        <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                    </a>
                </div>
                <!-- /.social-auth-links -->
                <p class="mb-0">
                    <a href="@Url.Action("Index","Site", new {area = ""})" class="text-center">Quay về trang người dùng</a>
                </p>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Public/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Public/dist/js/adminlte.min.js"></script>
</body>
</html>