MyStore/Controllers/MenuModuleController.cs
using MyClass.DAO;
using MyClass.Model;
using MyStore.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyStore.Controllers
{
    public class MenuModuleController : Controller
    {
        // GET: MenuModule
        private MyDBContext db = new MyDBContext();
        MenusDAO menusDAO = new MenusDAO();
        CategoriesDAO categoriesDAO = new CategoriesDAO();
        public ActionResult MainMenu()
        {
            var user = SessionConfig.GetUser();
            string userName = user != null ? user.Username : string.Empty;
            ViewBag.UserName = userName;
            return View(menusDAO.getListByParentId(0));
        }
    }
}

MyStore/Views/Shared/_LayoutSite.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Store</title>
    <!-- <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Porto - Bootstrap eCommerce Template">
    <meta name="author" content="SW-THEMES"> -->
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/Public/assets/images/icons/favicon.png">
    <script>
        WebFontConfig = {
            google: {
                families: ['Open+Sans:300,400,600,700,800', 'Poppins:300,400,500,600,700,800', 'Oswald:300,400,500,600,700,800']
            }
        };
        (function (d) {
            var wf = d.createElement('script'),
                s = d.scripts[0];
            wf.src = 'Public/assets/js/webfont.js';
            wf.async = true;
            s.parentNode.insertBefore(wf, s);
        })(document);
    </script>
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="~/Public/assets/css/bootstrap.min.css">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="~/Public/assets/css/demo4.min.css">
    <link rel="stylesheet" type="text/css" href="~/Public/assets/vendor/fontawesome-free/css/all.min.css">

    @RenderSection("head", required: false)
</head>
<body>
    <div class="page-wrapper">
        @Html.Action("MainMenu","MenuModule")
    </div>
    @RenderBody()
<footer class="footer bg-dark">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Thông tin liên hệ</h4>
                        <ul class="contact-info">
                            <li>
                                <span class="contact-info-label">Địa chỉ:</span>Nha Trang University
                            </li>
                            <li>
                                <span class="contact-info-label">Điện thoại:</span><a href="tel:">
                                    (84)
                                    0707197053
                                </a>
                            </li>
                            <li>
                                <span class="contact-info-label">Email:</span>baoworkings@gmail.com
                            </li>
                            <li>
                                <span class="contact-info-label">Thời gian mở cửa:</span> Thứ 2 - Thứ 6 / 7:00 AM
                                - 10:00 PM
                            </li>
                        </ul>
                        <div class="social-icons">
                            <a href="#" class="social-icon social-facebook icon-facebook" target="_blank"
                               title="Facebook"></a>
                            <a href="#" class="social-icon social-twitter icon-twitter" target="_blank"
                               title="Twitter"></a>
                            <a href="#" class="social-icon social-instagram icon-instagram" target="_blank"
                               title="Instagram"></a>
                        </div>
                        <!-- End .social-icons -->
                    </div>
                    <!-- End .widget -->
                </div>
                <!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4>

                        <ul class="links">
                            <li><a href="#">Help & FAQs</a></li>
                            <li><a href="#">Order Tracking</a></li>
                            <li><a href="#">Shipping & Delivery</a></li>
                            <li><a href="#">Orders History</a></li>
                            <li><a href="#">Advanced Search</a></li>
                            <li><a href="dashboard.html">My Account</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="#">Corporate Sales</a></li>
                            <li><a href="#">Privacy</a></li>
                        </ul>
                    </div>
                    <!-- End .widget -->
                </div>
                <!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Popular Tags</h4>

                        <div class="tagcloud">
                            <a href="#">Bag</a>
                            <a href="#">Black</a>
                            <a href="#">Blue</a>
                            <a href="#">Clothes</a>
                            <a href="#">Fashion</a>
                            <a href="#">Hub</a>
                            <a href="#">Shirt</a>
                            <a href="#">Shoes</a>
                            <a href="#">Skirt</a>
                            <a href="#">Sports</a>
                            <a href="#">Sweater</a>
                        </div>
                    </div>
                    <!-- End .widget -->
                </div>
                <!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget widget-newsletter">
                        <h4 class="widget-title">Subscribe newsletter</h4>
                        <p>
                            Get all the latest information on events, sales and offers. Sign up for newsletter:
                        </p>
                        <form action="#" class="mb-0">
                            <input type="email" class="form-control m-b-3" placeholder="Email address" required>

                            <input type="submit" class="btn btn-primary shadow-none" value="Subscribe">
                        </form>
                    </div>
                    <!-- End .widget -->
                </div>
                <!-- End .col-lg-3 -->
            </div>
            <!-- End .row -->
        </div>
        <!-- End .container -->
    </div>
    <!-- End .footer-middle -->

    <div class="container">
        <div class="footer-bottom">
            <div class="container d-sm-flex align-items-center">
                <div class="footer-left">
                    <span class="footer-copyright">© Bao Shop. 2023. All Rights Reserved</span>
                </div>

                <div class="footer-right ml-auto mt-1 mt-sm-0">
                    <div class="payment-icons">
                        <span class="payment-icon visa"
                              style="background-image: url(/Public/assets/images/payments/payment-visa.svg)"></span>
                        <span class="payment-icon paypal"
                              style="background-image: url(/Public/assets/images/payments/payment-paypal.svg)"></span>
                        <span class="payment-icon stripe"
                              style="background-image: url(/Public/assets/images/payments/payment-stripe.png)"></span>
                        <span class="payment-icon verisign"
                              style="background-image: url(/Public/assets/images/payments/payment-verisign.svg)"></span>
                    </div>
                </div>
            </div>
        </div>
        <!-- End .footer-bottom -->
    </div>
    <!-- End .container -->
</footer>
    <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="~/Public/assets/js/jquery.min.js"></script>
    <script src="~/Public/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/Public/assets/js/optional/isotope.pkgd.min.js"></script>
    <script src="~/Public/assets/js/plugins.min.js"></script>
    <script src="~/Public/assets/js/jquery.appear.min.js"></script>
    <script src="~/Public/assets/js/main.min.js"></script>
    <script>(function () { var js = "window['__CF$cv$params']={r:'82be8957ea6c4017',t:'MTcwMDk2NDAxMy43MzQwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='../../cdn-cgi/challenge-platform/h/g/scripts/jsd/9914b343/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);"; var _0xh = document.createElement('iframe'); _0xh.height = 1; _0xh.width = 1; _0xh.style.position = 'absolute'; _0xh.style.top = 0; _0xh.style.left = 0; _0xh.style.border = 'none'; _0xh.style.visibility = 'hidden'; document.body.appendChild(_0xh); function handler() { var _0xi = _0xh.contentDocument || _0xh.contentWindow.document; if (_0xi) { var _0xj = _0xi.createElement('script'); _0xj.innerHTML = js; _0xi.getElementsByTagName('head')[0].appendChild(_0xj); } } if (document.readyState !== 'loading') { handler(); } else if (window.addEventListener) { document.addEventListener('DOMContentLoaded', handler); } else { var prev = document.onreadystatechange || function () { }; document.onreadystatechange = function (e) { prev(e); if (document.readyState !== 'loading') { document.onreadystatechange = prev; handler(); } }; } })();</script>
</body>
</html>